language: csharp  
sudo: required  
dist: trusty  
mono: none
#dotnet: 3.0.100-preview8-013656
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta

before_script:
  - dotnet restore
  - dotnet --info

script:
  - dotnet test ./SwitchTest
